### ISSUE TITLE
Error on install: "gp_install_prompt:1: bad option: -t"

### ISSUE THREAD

**Issue by mattlinares** [magicmonty/bash-git-prompt#124] opened 2015-04-13 11:18 UTC
Trying simple install, but getting:

```
➜  ~  source ~/.bash-git-prompt/gitprompt.sh
gp_install_prompt:1: bad option: -t
gp_install_prompt:source:45: no such file or directory: /Users/mite/git-prompt-help.sh
```

Can you help! Thanks for the package..

**Comment by magicmonty** [comment] 2015-05-11 22:10
Which system are you on? Which version of Bash do you use? Maybe this could help

**Comment by allisonfong** [comment] 2015-06-23 00:23
+1 - reproduces using zsh (.zshrc)

**Comment by magicmonty** [comment] 2015-06-23 08:46
@allisonfong this is a prompt for Bash. For zsh there are better alternatives like https://github.com/robbyrussell/oh-my-zsh 
So I don't understand how to reproduce this with bash and zsh?

**Comment by magicmonty** [comment] 2015-08-13 18:29
@mattlinares I get this error, when I try to source this prompt on zsh, because there is no `-t` option on the builtin command `type`.

Do you use bash here? 
If not, can we close this bug?

**Comment by magicmonty** [comment] 2015-10-16 06:27
@mattlinares Is this stillhappening with the current version?

**Comment by magicmonty** [comment] 2015-12-24 13:39
Closed, as I have not enough information here and no answers;)

**Closed by magicmonty** 2015-12-24 13:39 UTC
