### ISSUE TITLE
failures on OSX 10.11.2 El Capitan

### ISSUE THREAD

**Issue by tansaku** [magicmonty/bash-git-prompt#231] opened 2016-03-02 11:10 UTC
Just tried to install as per instructions - with latest stable and config in .bash_profile:

```
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
    source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi`
```

got this:

```
MacBook-Pro:WebsiteOne tansaku$ source ~/.bash_profile 
-bash: /usr/local/Cellar/bash-git-prompt/2.4.1/share
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found./git-prompt-help.sh: No such file or directory
Cannot find prompt-colors.sh!
-bash: /usr/local/Cellar/bash-git-prompt/2.4.1/share
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

and that repeats and I never got access to the console.

I deleted that from .bash_profile, uninstalled and reinstalled the HEAD version, following the printed out instructions to adjust the .bashrc file, but got essentially the same problem:

```
Samuels-MBP:WebsiteOne tansaku$ brew install --HEAD bash-git-prompt
==> Cloning https://github.com/magicmonty/bash-git-prompt.git
Cloning into '/Library/Caches/Homebrew/bash-git-prompt--git'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 38 (delta 14), reused 12 (delta 7), pack-reused 0
Unpacking objects: 100% (38/38), done.
Checking connectivity... done.
==> Checking out branch master
==> Caveats
You should add the following to your .bashrc (or equivalent):
  if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
    GIT_PROMPT_THEME=Default
    source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
  fi
==> Summary
🍺  /usr/local/Cellar/bash-git-prompt/HEAD: 32 files, 77K, built in 1 second
Samuels-MBP:WebsiteOne tansaku$ source ~/.bashrc
-bash: /usr/local/Cellar/bash-git-prompt/HEAD/share
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed./git-prompt-help.sh: No such file or directory
Cannot find prompt-colors.sh!
-bash: /usr/local/Cellar/bash-git-prompt/HEAD/share
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed./themes/Default.bgptheme: No such file or directory
-bash: /usr/local/Cellar/bash-git-prompt/HEAD/share
Saving session...
```

again it would not give me access to the console again, so I'm stuck there ...

**Comment by magicmonty** [comment] 2016-03-03 08:07
I cannot reproduce this. What is this stuff about "shared history" etc? Maybe there is some mechanism on your bash to save the current state of the bash prompt, which has to be reset? After an update the bash shell must be restarted completely

**Comment by rtirserio** [comment] 2016-03-04 14:41
@tansaku I was seeing this as well, it appears to be a problem with the saving of bash sessions. if you `touch ~/.bash_sessions_disable` things go back to normal.

**Comment by simleap** [comment] 2016-03-16 16:16
@rtirserio, thanks for your magic command!

**Comment by ashaikh** [comment] 2016-05-07 06:57
@rtirserio Not sure how you figured that out but thank you for the help!

**Comment by ashaikh** [comment] 2016-05-07 06:59
@magicmonty This seemed to happen just after running a brew cleanup so it may have to do something with that.

**Comment by unforswearing** [comment] 2016-06-12 21:46
same issue here (though I'm still on Yosemite), fixed with @tansaku's awesome help. Can also confirm that the issue appeared after `brew cleanup` as @ashaikh mentioned.

**Comment by AaronM04** [comment] 2016-07-28 23:42
I think `touch ~/.bash_sessions_disable` just papers over the actual problem. The ideal solution would be to make bash-git-prompt compatible with El Capitan's default setting in my opinion.

**Comment by heisian** [comment] 2016-08-19 22:22
Yes, there needs to be an update here.

I got the same problem by running these commands:

```
mkdir ~/bin && cd ~/bin
git clone https://github.com/magicmonty/bash-git-prompt.git .bash-git-prompt --depth=1\
source ~/bin/.bash-git-prompt/gitprompt.sh >> ~/.bash_profile
GIT_PROMPT_ONLY_IN_REPO=1 >> ~/.bash_profile
source ~/.bash_profile
```

Produces:
```
-bash: /Users/heisian/bin/.bash-git-prompt
Saving session...
...copying shared history...
...saving history...
...completed./git-prompt-help.sh: No such file or directory
```

Disabling bash sessions fixes the problem, but like @AaronM04 it's a band-aid.

**Comment by ogr3** [comment] 2016-08-20 08:53
The problem for me, running two Macs (MBP late 2011 and 2013), is that I switched to iTerm2 a long time ago, so I'm not running the stock terminal app.  I haven't had time to read up on the changes Apple made with bash sessions, and subsequently what makes them break this prompt. And since @magicmonty doesn't seem affected either, I'm guessing he doesn't run the stock terminal app either, or that macs that are upgraded don't get bash sessions installed.

**Comment by magicmonty** [comment] 2016-08-20 14:04
I'm also not affected, as I also don't use the stock terminal. Also most of the time I use zsh now.

**Comment by magicmonty** [comment] 2016-08-20 14:11
I just tried it with bash (homebrew version) as login shell and stock terminal app. For me nothing of this seems to happen. I run on a MPB (late 2012) with Yosemite installed. How can I enable the bash session feature? maybe this is something in the .bashrc or .bashprofile, I don't have?

**Comment by magicmonty** [comment] 2016-08-20 14:26
On further lookup the session stuff is coded in `/etc/bashrc_Apple_Terminal`. The problem lies maybe here:

> Note that this uses PROMPT_COMMAND to enable per-session history
   the first time for each new session. If you customize PROMPT_COMMAND
   be sure to include the previous value. e.g., 
   PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }your_code_here"

**Comment by ogr3** [comment] 2016-08-20 15:13
on my OS X after starting terminal you get this:

```sh
$ echo $PROMPT_COMMAND 
setLastCommandState;update_terminal_cwd;setGitPrompt
```

So apple adds the function `update_terminal_cwd` to the `PROMPT_COMMAND` variable.

If someone here modifies their PROMPT_COMMAND that would indeed be interesting.

**Closed** 2023-11-24 06:18 UTC
