### ISSUE TITLE
Error message in prompt with old bash version

### ISSUE THREAD

**Issue by tiagocoutinho** [magicmonty/bash-git-prompt#252] opened 2016-06-02 06:09 UTC
Hi,
I have some machines with an old bash version (4.1.5) which I cannot update.
When I activate bash-git-prompt I receive an error message after each prompt:

    bash: test: -eq: unary operator expected

I think I found a solution. Will propose a PR in a few minutes

**Comment by ogr3** [comment] 2016-06-02 07:46
Looks like a typo in the original code, since it escapes `$GIT_$1` in double quotes in the other branch. The patched version works well in modern Bash (4.3.11, Ubuntu). 

I cannot, however reproduce the bug on old bash (4.1.2, CentOS 6). The proposed patch works though, so I'm all for that this get merged.

**Comment by magicmonty** [comment] 2016-06-02 11:49
Should be solved with #253

**Closed by magicmonty** 2016-06-02 11:49 UTC

**Comment by ogr3** [comment] 2016-06-03 20:59
I suspect something is fishy in your environment. -eq behaves like this if a variable is not set and you do a test like

`eval test $GIT_CLEAN -eq 1`

if  $GIT_CLEAN is not set you get the error message

`bash: test: -eq: unary operator expected`

So I'd start looking in the code for places where it uses -eq and do debug printouts to see if the variable checked against has been set.

**Comment by magicmonty** [comment] 2016-06-06 10:56
should be fixed now with #254
